// -*- C++ -*- generated by wxGlade 0.4.1 on Mon May 21 17:03:19 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef MYDAYINFODIALOG_H
#define MYDAYINFODIALOG_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

class MyDayInfoPlot:public wxScrolledWindow
{
    public:
        MyDayInfoPlot(wxWindow *parent, int id);
        virtual void OnDraw(wxDC& dc);
        void DrawPricePlot(wxDC&dc);
};

class MyDayInfoDialog: public wxDialog {
public:
    // begin wxGlade: MyDayInfoDialog::ids
    // end wxGlade

    MyDayInfoDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: MyDayInfoDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyDayInfoDialog::attributes
    MyDayInfoPlot* window_1;
    wxStaticLine* static_line_5;
    wxButton* button_7;
    // end wxGlade
}; // wxGlade: end class


#endif // MYDAYINFODIALOG_H
