// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Mar  8 13:37:11 2007

#include <wx/wx.h>
#include <wx/image.h>
#include "stocks.h"

#ifndef MYSTOCKDETAIL_H
#define MYSTOCKDETAIL_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
#include <wx/grid.h>
// end wxGlade


class mystockdetail: public wxDialog {
public:
    // begin wxGlade: mystockdetail::ids
    // end wxGlade

    mystockdetail(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    void SetMyStock(MyStockStru* s);
private:
    // begin wxGlade: mystockdetail::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: mystockdetail::attributes
    wxGrid* grid_detail;
    wxStaticLine* static_line_4;
    wxButton* button_4;
    // end wxGlade
}; // wxGlade: end class


#endif // MYSTOCKDETAIL_H
