// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Mar  1 16:31:25 2007

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/valgen.h>
#include "stocks.h"

#ifndef MYSTOCKDIALOG_H
#define MYSTOCKDIALOG_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

#include "wstockgeturl.h"

class wxStockIdValidator: public wxGenericValidator
{
public:
	wxStockIdValidator(wxString *v):wxGenericValidator(v){};
	virtual bool Validate(wxWindow * parent);
	virtual wxObject *Clone() const { 
		wxStockIdValidator*pv= new wxStockIdValidator(m_pString); 
		return pv;
	}
};


class wxDoubleValidator: public wxValidator
{
public:
  wxDoubleValidator(double* val){v=val;};
  ~wxDoubleValidator(){};
  virtual wxObject *Clone() const { return new wxDoubleValidator(v); }
  wxDoubleValidator(const wxDoubleValidator& val)
    : wxValidator()
  {
     v= val.v;
  };
  virtual bool Validate(wxWindow * WXUNUSED(parent)) {
      return true;
  }
  virtual bool TransferToWindow(){
      if ( !m_validatorWindow )
        return false;

    if (m_validatorWindow->IsKindOf(CLASSINFO(wxTextCtrl)) )
    {
        wxTextCtrl* pControl = (wxTextCtrl*) m_validatorWindow;
        if (v)
        {
            pControl->SetValue(wxString::Format(wxT("%.2f"),*v));
            return true;
        }
    }
    return false;
};
  virtual bool TransferFromWindow(){
    if ( !m_validatorWindow )
        return false;

    if (m_validatorWindow->IsKindOf(CLASSINFO(wxTextCtrl)) )
    {
        wxTextCtrl* pControl = (wxTextCtrl*) m_validatorWindow;
        if (v)
        {
            pControl->GetValue().ToDouble(v);
            return true;
        }
    }
    return false;
  };
protected:
    double *v;
};

class MyStockDialogData
{
 public:
    MyStockDialogData(){
        StockId=wxT("600171");
        ACount=3100;
        Price=3.87;
        Op=0;
    };
    MyStockDialogData(wxString id, int a, double p,int op){
        StockId = id;
        ACount = a;
        Price = p;
        Op = op;
    };
    MyStockDialogData(const MyStockDialogData& v){
        StockId = v.StockId;
        ACount = v.ACount;
        Price = v.Price;
        Op = v.Op;
    };
    MyStockDialogData & operator = (const MyStockDialogData& v){
        StockId = v.StockId;
        ACount = v.ACount;
        Price = v.Price;
        Op = v.Op;
        return *this;
    };
    wxString StockId;
    int ACount;
    int Op;
    double Price;
};


class MyStockDialog: public wxDialog {
public:
    // begin wxGlade: MyStockDialog::ids
    // end wxGlade

    MyStockDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    void SetData(const MyStockDialogData& d){
        data=d;
        TransferDataToWindow();
    };
    const MyStockDialogData& GetData(){return data;};
	void SetStocks(Stocks *ss){
		validateStocks = ss;
	};
	Stocks*GetValidateStocks(){return validateStocks;};
private:
    // begin wxGlade: MyStockDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    MyStockDialogData data;

protected:
	Stocks* validateStocks;

    // begin wxGlade: MyStockDialog::attributes
    wxStaticText* label_1;
    wxTextCtrl* t_stockid;
    wxStaticText* label_13;
    wxTextCtrl* text_stockname;
    wxStaticText* label_2;
    wxTextCtrl* t_acount;
    wxStaticText* label_3;
    wxTextCtrl* t_price;
    wxStaticText* label_9;
    wxComboBox* c_op;
    wxStaticLine* static_line_2;
    wxButton* button_2;
    wxButton* button_3;
    // end wxGlade
    void OnEnterProcess(wxCommandEvent &event); // wxGlade: <event_handler>
	void OnUrlValidDone(wxStockValidateDoneEvent &event);
protected:
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // MYSTOCKDIALOG_H
