// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Feb 26 17:05:25 2007

#include <wx/wx.h>
#include <wx/image.h>

#include "stockplot.h"

#ifndef STOCKHISTORYDIALOG_H
#define STOCKHISTORYDIALOG_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


class StockHistoryDialog: public wxDialog {
public:
    // begin wxGlade: StockHistoryDialog::ids
    // end wxGlade

    StockHistoryDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxSize(100,100), long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: StockHistoryDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: StockHistoryDialog::attributes
    wxPlotWindow* m_chart;
    wxStaticText* label_1;
    wxStaticText* label_2;
    wxStaticLine* static_line_1;
    wxButton* button_1;
    // end wxGlade
}; // wxGlade: end class


#endif // STOCKHISTORYDIALOG_H
