// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Mar  6 10:31:42 2007

#include "wstockcustomdialog.h"
#include "wstockconfig.h"

wstockcustomdialog::wstockcustomdialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: wstockcustomdialog::wstockcustomdialog
    notebook_1 = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, wxNB_LEFT);
    notebook_1_pane_2 = new wxPanel(notebook_1, -1);
    notebook_1_pane_1 = new wxPanel(notebook_1, -1);
    label_4 = new wxStaticText(notebook_1_pane_1, -1, wxT("Keys Path:"));
    text_keypath = new wxTextCtrl(notebook_1_pane_1, -1, wxT(""));
    label_5 = new wxStaticText(notebook_1_pane_1, -1, wxT("History Dir:"));
    text_history_dir = new wxTextCtrl(notebook_1_pane_1, -1, wxT(""));
    label_6 = new wxStaticText(notebook_1_pane_2, -1, wxT("GoogleAcount:"));
    text_gacount = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""));
    label_7 = new wxStaticText(notebook_1_pane_2, -1, wxT("GooglePasswd:"));
    text_gpasswd = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    label_8 = new wxStaticText(notebook_1_pane_2, -1, wxT("MystocksTitle:"));
    text_gstock_title = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""));
    static_line_3 = new wxStaticLine(this, -1);
    button_5 = new wxButton(this, wxID_CANCEL, wxT(""));
    button_6 = new wxButton(this, wxID_OK, wxT(""));

    set_properties();
    do_layout();
    // end wxGlade
}


void wstockcustomdialog::set_properties()
{
    // begin wxGlade: wstockcustomdialog::set_properties
    // end wxGlade
    text_keypath->SetValue(WStockConfig::GetKeyPath());
    text_history_dir->SetValue(WStockConfig::GetHistoryDataDir());
    text_gacount->SetValue(WStockConfig::GetGmailUserName());
    text_gpasswd->SetValue(WStockConfig::GetGmailPasswd());
    text_gstock_title->SetValue(WStockConfig::GetGoogleMystockTitle());
}

extern wxConfig config;
void wstockcustomdialog::StoreSettings(void){
    WStockConfig::SetGmailPasswd(text_gpasswd->GetValue());
    WStockConfig::SetGmailUserName(text_gacount->GetValue());
    WStockConfig::SetGoogleMystockTitle(text_gstock_title->GetValue());
    WStockConfig::SetHistoryDataDir(text_history_dir->GetValue());
    WStockConfig::SetKeyPath(text_keypath->GetValue());
    config.Flush(true);
}

void wstockcustomdialog::do_layout()
{
    // begin wxGlade: wstockcustomdialog::do_layout
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_3 = new wxFlexGridSizer(3, 2, 0, 0);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(2, 2, 0, 0);
    grid_sizer_2->Add(label_4, 0, wxALL|wxALIGN_RIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_2->Add(text_keypath, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    grid_sizer_2->Add(label_5, 0, wxALL|wxALIGN_RIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_2->Add(text_history_dir, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    grid_sizer_2->AddGrowableCol(1);
    sizer_8->Add(grid_sizer_2, 1, wxEXPAND, 0);
    notebook_1_pane_1->SetAutoLayout(true);
    notebook_1_pane_1->SetSizer(sizer_8);
    sizer_8->Fit(notebook_1_pane_1);
    sizer_8->SetSizeHints(notebook_1_pane_1);
    grid_sizer_3->Add(label_6, 0, wxALL|wxALIGN_RIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_3->Add(text_gacount, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(label_7, 0, wxALL|wxALIGN_RIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_3->Add(text_gpasswd, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    grid_sizer_3->Add(label_8, 0, wxALL|wxALIGN_RIGHT|wxADJUST_MINSIZE, 5);
    grid_sizer_3->Add(text_gstock_title, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    notebook_1_pane_2->SetAutoLayout(true);
    notebook_1_pane_2->SetSizer(grid_sizer_3);
    grid_sizer_3->Fit(notebook_1_pane_2);
    grid_sizer_3->SetSizeHints(notebook_1_pane_2);
    grid_sizer_3->AddGrowableCol(1);
    notebook_1->AddPage(notebook_1_pane_1, wxT("Generic"));
    notebook_1->AddPage(notebook_1_pane_2, wxT("Google"));
    sizer_6->Add(notebook_1, 1, wxEXPAND, 0);
    sizer_6->Add(static_line_3, 0, wxEXPAND, 0);
    sizer_7->Add(20, 20, 1, wxADJUST_MINSIZE, 0);
    sizer_7->Add(button_5, 0, wxALL|wxADJUST_MINSIZE, 5);
    sizer_7->Add(button_6, 0, wxALL|wxADJUST_MINSIZE, 5);
    sizer_6->Add(sizer_7, 0, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_6);
    sizer_6->Fit(this);
    sizer_6->SetSizeHints(this);
    Layout();
    // end wxGlade
}

