// -*- C++ -*- generated by wxGlade 0.4.1 on Thu Mar  8 13:37:11 2007

#include "mystockdetail.h"

void mystockdetail::SetMyStock(MyStockStru* s){
        if (grid_detail->GetNumberRows()< (int)s->buyinfos.size()+2){
            grid_detail->AppendRows(s->buyinfos.size()+2 - grid_detail->GetNumberRows());
        }
        else if (grid_detail->GetNumberRows()> (int)s->buyinfos.size()+2){
            grid_detail->DeleteRows(grid_detail->GetNumberRows()-s->buyinfos.size()-2);
        }
        BuyInfoList::Node* node = s->buyinfos.GetFirst();
        int i=0;
        wxString Ops[]={
            _("Buy"),
            _("Sell"),
        };
        while (node)
        {
            BuyInfo* pbuyinfo = node->GetData();
            grid_detail->SetCellValue(i,0,pbuyinfo->data.Format(wxT("%Y-%m-%d")));
            grid_detail->SetCellValue(i,1,Ops[pbuyinfo->Op]);
            grid_detail->SetCellValue(i,2,wxString::Format(wxT("%d"),pbuyinfo->BuyAmount));
            grid_detail->SetCellValue(i,3,wxString::Format(wxT("%.2f"),pbuyinfo->BuyPrice));
            if (pbuyinfo->Op == 0){
                grid_detail->SetCellValue(i,4,wxString::Format(wxT("%.2f"), -pbuyinfo->BuyAmount * pbuyinfo->BuyPrice*1.005));
            }
            else{
                grid_detail->SetCellValue(i,4,wxString::Format(wxT("%.2f"), pbuyinfo->BuyAmount * pbuyinfo->BuyPrice*0.995));
            }
            node = node->GetNext();
            i++;
        }
        double CurValue=0;
        s->stock->GetPropertyValue(_("PRICE")).ToDouble(&CurValue);
        grid_detail->SetCellValue(i,4,wxString::Format(wxT("%.2f"), -s->GetTotalPay()));
        grid_detail->SetCellValue(i+1,0,wxString::Format(wxT("%.2f"), s->GetCurValue(CurValue)));
        grid_detail->SetCellValue(i+1,1,wxString::Format(wxT("%.2f"), -s->GetTotalPay()));
        grid_detail->SetCellValue(i+1,2,wxString::Format(wxT("%.2f"), s->GetCurValue(CurValue)-s->GetTotalPay()));
}

mystockdetail::mystockdetail(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: mystockdetail::mystockdetail
    grid_detail = new wxGrid(this, -1);
    static_line_4 = new wxStaticLine(this, -1);
    button_4 = new wxButton(this, wxID_OK, wxT(""));

    set_properties();
    do_layout();
    // end wxGlade
}


void mystockdetail::set_properties()
{
    // begin wxGlade: mystockdetail::set_properties
    SetSize(wxSize(452, 284));
    grid_detail->CreateGrid(1, 5);
    grid_detail->SetColLabelValue(0, _("Date"));
    grid_detail->SetColLabelValue(1, _("Operate"));
    grid_detail->SetColLabelValue(2, _("Amount"));
    grid_detail->SetColLabelValue(3, _("Price"));
    grid_detail->SetColLabelValue(4, _("Total"));
    // end wxGlade
    grid_detail->SetRowLabelSize(30);
    grid_detail->SetDefaultCellAlignment(wxALIGN_CENTRE,wxALIGN_CENTRE);
    grid_detail->EnableEditing(false);
}


void mystockdetail::do_layout()
{
    // begin wxGlade: mystockdetail::do_layout
    wxBoxSizer* sizer_11 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_12 = new wxBoxSizer(wxHORIZONTAL);
    sizer_11->Add(grid_detail, 1, wxEXPAND, 0);
    sizer_11->Add(static_line_4, 0, wxEXPAND, 0);
    sizer_12->Add(20, 20, 1, wxADJUST_MINSIZE, 0);
    sizer_12->Add(button_4, 0, wxALL|wxADJUST_MINSIZE, 5);
    sizer_11->Add(sizer_12, 0, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_11);
    Layout();
    // end wxGlade
}

