// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Mar  6 10:31:42 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WSTOCKCUSTOMDIALOG_H
#define WSTOCKCUSTOMDIALOG_H

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/statline.h>
// end wxGlade


class wstockcustomdialog: public wxDialog {
public:
    // begin wxGlade: wstockcustomdialog::ids
    // end wxGlade

    wstockcustomdialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    void StoreSettings(void);

private:
    // begin wxGlade: wstockcustomdialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wstockcustomdialog::attributes
    wxStaticText* label_4;
    wxTextCtrl* text_keypath;
    wxStaticText* label_5;
    wxTextCtrl* text_history_dir;
    wxPanel* notebook_1_pane_1;
    wxStaticText* label_6;
    wxTextCtrl* text_gacount;
    wxStaticText* label_7;
    wxTextCtrl* text_gpasswd;
    wxStaticText* label_8;
    wxTextCtrl* text_gstock_title;
    wxPanel* notebook_1_pane_2;
    wxStaticText* label_10;
    wxTextCtrl* text_curl_proxy;
    wxStaticText* label_11;
    wxTextCtrl* text_curl_userpwd;
    wxStaticText* label_12;
    wxComboBox* combo_curl_auth;
    wxCheckBox* checkbox_curl_noproxy;
    wxPanel* notebook_1_pane_3;
    wxNotebook* notebook_1;
    wxStaticLine* static_line_3;
    wxButton* button_5;
    wxButton* button_6;
    // end wxGlade
}; // wxGlade: end class


#endif // WSTOCKCUSTOMDIALOG_H
