// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Mar 13 15:25:55 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef WSTOCKGLOBALINFO_H
#define WSTOCKGLOBALINFO_H

// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

#include "stocks.h"
#include "wx/timer.h"

enum{
	KT_FIXED,
	KT_REALTIME,
	KT_GLOBAL_REALTIME,
	KT_REALTIME_CALC,
	KT_HISTORY_CALC,
	KT_MYSTOCK_FIXED,
	KT_MYSTOCK_REALTIME,
};

enum{
	VT_COLOR_NUMBER,
	VT_NUMBER,
	VT_OTHER
};

class MainGridDef_Stru:public wxObject{
public:
	MainGridDef_Stru(const wxString &k, int kt,int vt,int cc=-1){
		KeyName = k;
		KeyType = kt;
		ValueType = vt;
		ColorCol = cc;
	};
	wxString KeyName;
	int KeyType; //0:Fixed 1: RealTime 2:RealTimeCalc 3:HistoryCalc
	int ValueType; //0: Number With Color 1:Number Without Color 2:Other
	int ColorCol;
};
WX_DECLARE_LIST(MainGridDef_Stru,MainGridDef_StruList);

class wstockglobalinfo: public wxDialog {
public:
    // begin wxGlade: wstockglobalinfo::ids
    // end wxGlade

    wstockglobalinfo(wxWindow* parent, int id, const wxString& title, MyStocks*ms, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    void UpdateRealtimeCell();
private:
    // begin wxGlade: wstockglobalinfo::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    void OnStockDataGetDone(wxStockDataGetDoneEvent&event);
    void OnRealtimeDeltaTimer(wxTimerEvent& event);
    void UpdateInfoGridCellColor(int r);
    void UpdateInfoGridCell(int r);
protected:
    // begin wxGlade: wstockglobalinfo::attributes
    wxGrid* grid_infos;
    // end wxGlade
    MainGridDef_StruList ColDefs;
    StockList stocks;
    MyStocks *mystocks;
    StocksDataFetch*fetchObj;
    wxTimer RealTimeDeltaTimer;
    DECLARE_EVENT_TABLE();
}; // wxGlade: end class


#endif // WSTOCKGLOBALINFO_H
